### ISSUE TITLE
problems with ./accept-new-host-keys.py

### ISSUE THREAD

**Issue by Agilitytime** [opthomas-prime/hcloud_swarm#1]
Hi,

after i run ./accept-new-host-keys.py

i became this error.
The python-terraform module is installed.

Thanks,
Basti

./accept-new-host-keys.py
Traceback (most recent call last):
  File "./accept-new-host-keys.py", line 21, in <module>
    main()
  File "./accept-new-host-keys.py", line 13, in main
    state = json.dumps(t.tfstate.modules)
AttributeError: 'Tfstate' object has no attribute 'modules'

**Comment by tmsmr** [comment]
Hey @Agilitytime,
did you install the terraform module for Python?
Well, AFAIK this was broken anyway. Would you please check if `./terraform-swarm-inventory.py --accept` on the linked Branch/PR works for you?

**Comment by Agilitytime** [comment]
Hey Thomas,

yes, works without problems!

Best,
Basti

**Comment by tmsmr** [comment]
Merged in master...
