### ISSUE TITLE
ansible-galaxy install --roles-path . -r requirements.yml - Is not work

### ISSUE THREAD

**Issue by eibrahimov** [opthomas-prime/hcloud_swarm#3]
👋  when I try this command ansible can't reach requirements.yml. Because file is not in repository.

Change into 'roles' and install dependencies: ansible-galaxy install --roles-path . -r requirements.yml

**Comment by tmsmr** [comment]
Hi @eibrahimov, If you don't want to install custom roles, just skip that command!

As you can see the last changes on this repo were some time ago: Feel free to use it as inspiration and/or as guide, but i don't maintain this actively anymore...

**Comment by tmsmr** [comment]
I'm closing this issue now, feel free to repoen it if you have further questions!
